version: '3.7'

services:
  jenkins:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile
    container_name: jenkins
    restart: always
    volumes:
      - $HOME/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    environment:
      - VIRTUAL_PORT=8080
